# Generated by Django 6.1 on 2026-08-31 06:38

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', models.TextField(blank=True)),
                ('body', wagtail.fields.StreamField([('stats', 3), ('process', 9), ('testimonials', 13), ('faqs', 17), ('section', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 4.5%, 90 min, 40', 'max_length': 20}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 2: ('wagtail.blocks.StructBlock', [[('value', 0), ('label', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'icon': 'form'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 4.40 am', 'max_length': 20, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 6: ('wagtail.blocks.TextBlock', (), {'required': False}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('time', 4), ('title', 5), ('body', 6), ('image', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'icon': 'time'}), 10: ('wagtail.blocks.TextBlock', (), {}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('quote', 10), ('name', 5), ('place', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'icon': 'openquote'}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 15: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul']}), 16: ('wagtail.blocks.StructBlock', [[('question', 14), ('answer', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'icon': 'help'}), 18: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 19: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 20: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Image left'), ('right', 'Image right'), ('wide', 'Full width')]}), 22: ('wagtail.blocks.StructBlock', [[('eyebrow', 18), ('heading', 19), ('body', 20), ('image', 7), ('layout', 21)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('hero_eyebrow', models.CharField(blank=True, default='Suratgarh, Rajasthan', max_length=80)),
                ('hero_heading', models.CharField(default='Milk that never sees a warehouse.', max_length=140)),
                ('hero_subheading', models.TextField(blank=True, default='Drawn at first light from our own cows and buffaloes, and at your door before the day gets warm.')),
                ('hero_cta_label', models.CharField(blank=True, default='Start a subscription', max_length=40)),
                ('story_heading', models.CharField(blank=True, default='One farm. Two milkings. No middle.', max_length=140)),
                ('story_body', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('stats', 3), ('process', 9), ('testimonials', 13), ('faqs', 17), ('section', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 4.5%, 90 min, 40', 'max_length': 20}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 2: ('wagtail.blocks.StructBlock', [[('value', 0), ('label', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'icon': 'form'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 4.40 am', 'max_length': 20, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 6: ('wagtail.blocks.TextBlock', (), {'required': False}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('time', 4), ('title', 5), ('body', 6), ('image', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'icon': 'time'}), 10: ('wagtail.blocks.TextBlock', (), {}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('quote', 10), ('name', 5), ('place', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'icon': 'openquote'}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 15: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul']}), 16: ('wagtail.blocks.StructBlock', [[('question', 14), ('answer', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'icon': 'help'}), 18: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 19: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 20: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Image left'), ('right', 'Image right'), ('wide', 'Full width')]}), 22: ('wagtail.blocks.StructBlock', [[('eyebrow', 18), ('heading', 19), ('body', 20), ('image', 7), ('layout', 21)]], {})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
