# Generated by Django 6.1 on 2026-08-31 06:38

import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
import wagtail.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=140)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('milk', 'Milk'), ('ghee', 'Ghee'), ('curd', 'Curd'), ('chhach', 'Chhach')], default='milk', max_length=12)),
                ('animal', models.CharField(choices=[('cow', 'Cow'), ('buffalo', 'Buffalo'), ('mixed', 'Cow + Buffalo'), ('none', 'Not applicable')], default='cow', max_length=10)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('badge', models.CharField(blank=True, help_text='e.g. Bestseller, A2, Farm favourite', max_length=30)),
                ('fat_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('snf_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('shelf_life', models.CharField(blank=True, default='Same day', max_length=80)),
                ('accent', models.CharField(default='#E8B04B', help_text='Hex colour used on the storefront card', max_length=7)),
                ('is_subscribable', models.BooleanField(default=True)),
                ('available_morning', models.BooleanField(default=True)),
                ('available_evening', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
            bases=(models.Model, modelsearch.index.Indexed),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(help_text='e.g. 500 ml, 1 litre, 250 g', max_length=40)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=6)),
                ('unit', models.CharField(choices=[('L', 'litre'), ('ml', 'millilitre'), ('kg', 'kilogram'), ('g', 'gram')], default='L', max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sku', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'verbose_name': 'pack size',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
