# Generated by Django 6.1 on 2026-08-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='accent',
            field=models.CharField(default='#C6F24B', help_text='Hex colour used on the storefront card', max_length=7),
        ),
    ]
