# Generated by Django 6.1 on 2026-09-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_accent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(default='milk', help_text='What sort of product, e.g. milk, ghee, paneer', max_length=30),
        ),
    ]
