# Generated by Django 6.1 on 2026-09-11 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        ('subscriptions', '0003_alter_package_accent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deliveries', to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deliveries', to='subscriptions.subscriptionline'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deliveries', to='subscriptions.subscription'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='accounts.address'),
        ),
    ]
