# Generated by Django 6.1 on 2026-08-31 06:38

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('serves', models.CharField(blank=True, help_text='e.g. A family of four', max_length=60)),
                ('accent', models.CharField(default='#B4623A', max_length=7)),
                ('discount_percent', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('slot', models.CharField(choices=[('morning', 'Morning (5.30 – 8.00 am)'), ('evening', 'Evening (5.00 – 7.30 pm)')], default='morning', max_length=10)),
                ('frequency', models.CharField(choices=[('daily', 'Every day'), ('alternate', 'Every other day'), ('weekdays', 'Chosen days of the week')], default='daily', max_length=12)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('package', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.package')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_items', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'package item',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=10)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('resume_on', models.DateField(blank=True, help_text='Set when paused until a fixed date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='accounts.address')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, help_text='Default packs per delivery')),
                ('slot', models.CharField(choices=[('morning', 'Morning (5.30 – 8.00 am)'), ('evening', 'Evening (5.00 – 7.30 pm)')], default='morning', max_length=10)),
                ('frequency', models.CharField(choices=[('daily', 'Every day'), ('alternate', 'Every other day'), ('weekdays', 'Chosen days of the week')], default='daily', max_length=12)),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='0=Monday .. 6=Sunday')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='subscriptions.subscription')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_lines', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['slot', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DayOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='subscriptions.subscriptionline')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('line', 'date'), name='unique_override_per_day')],
            },
        ),
    ]
