# Generated by Django 6.1 on 2026-08-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitem',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Every day'), ('alternate', 'Every other day'), ('weekdays', 'Chosen days of the week'), ('monthly', 'Once a month')], default='daily', max_length=12),
        ),
        migrations.AlterField(
            model_name='subscriptionline',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Every day'), ('alternate', 'Every other day'), ('weekdays', 'Chosen days of the week'), ('monthly', 'Once a month')], default='daily', max_length=12),
        ),
    ]
