# Generated by Django 6.1 on 2026-08-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_packageitem_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='accent',
            field=models.CharField(default='#0E6B4B', max_length=7),
        ),
    ]
