# Generated by Django 6.1 on 2026-09-11 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('subscriptions', '0003_alter_package_accent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='accounts.address'),
        ),
    ]
