# Generated by Django 6.1 on 2026-09-14 06:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_product_accent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='What customers type, e.g. FIRSTLIGHT20', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Shown in the wallet next to the credit', max_length=120)),
                ('kind', models.CharField(choices=[('percent_month', "Per cent of the basket's month"), ('fixed', 'Fixed amount'), ('pack', 'Price of one pack')], default='fixed', max_length=16)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Per cent for 'per cent of the basket's month', rupees for 'fixed amount'", max_digits=8)),
                ('max_credit', models.DecimalField(blank=True, decimal_places=2, help_text='The most one household can get', max_digits=8, null=True)),
                ('min_monthly', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The basket must come to at least this much a month', max_digits=10)),
                ('new_customers_only', models.BooleanField(default=False, help_text='Only households yet to get a delivery')),
                ('is_active', models.BooleanField(default=True)),
                ('ends_on', models.DateField(blank=True, help_text='The last day the code works', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(blank=True, help_text="For 'price of one pack': the pack whose price is credited", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_referral', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referrer_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('referrer_paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='offers.coupon')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('coupon__isnull', False)), fields=('user', 'coupon'), name='one_use_of_a_code_per_customer'), models.UniqueConstraint(condition=models.Q(('is_referral', True)), fields=('user',), name='one_referral_per_customer')],
            },
        ),
    ]
